displayName=Player Examine
author=Aiirik
description=Shows visible equipment and combat info for examined players
tags=player, examine, equipment, stats, tooltip, overlay, playerexamine,
version=1.1.2
plugins=com.aiirik.playerexamine.PlayerExaminePlugin
build=standard
