displayName=Player Examine
author=Aiirik
description=Shows visible equipment and combat info for examined players
tags=
version=1.0.0
plugins=com.aiirik.playerexamine.PlayerExaminePlugin
build=standard
